"""Create product table

Revision ID: 215fb7216fb2
Revises: 
Create Date: 2021-03-18 17:19:10.102054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215fb7216fb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
